baseURL = "https://blackbeard.netlify.com/"
languageCode = "en-us"

title = "Blackbeard"
theme = "kraiklyn"
contentDir = "./blackbeard/docs/"
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
googleAnalytics = "UA-122674263-1"

pygmentsStyle = "dracula"
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
externalTitle = "Contributing to Blackbeard"
sidebarColor = "blue"
customCss = ["css/syntax.css"]

[[menu.shortcuts]]
name = "Blackbeard on Github"
url = "https://github.com/Meetic/blackbeard"
weight = 10

[[menu.shortcuts]]
name = "Contribution guide"
url = "https://github.com/Meetic/blackbeard/blob/master/CONTRIBUTING.MD"
weight = 20
