baseURL = "http://k8s-blackbeard.github.io"
languageCode = "en-us"

title = "Blackbeard"
theme = "kraiklyn"
contentDir = "./blackbeard/docs/"

pygmentsStyle = "dracula"
# pygmentsStyle = "trac"
# pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
externalTitle = "Blackbeard documentation"
sidebarColor = "blue"
customCss = ["css/syntax.css"]

[[menu.shortcuts]]
name = "Kraiklyn on Github"
url = "https://github.com/jsnjack/kraiklyn"
weight = 10

[[menu.shortcuts]]
name = "Hugo docs"
url = "https://gohugo.io/documentation/"
weight = 20
